//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdensServicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdensServicos()
        {
            this.OrdensServicosMateriais = new HashSet<OrdensServicosMateriais>();
            this.OrdensServicosServicos = new HashSet<OrdensServicosServicos>();
        }
    
        public int Id { get; set; }
        public string CodigoOrdensServicos { get; set; }
        public int ClienteId { get; set; }
        public int VeiculosId { get; set; }
        public int FuncionarioResponsavel { get; set; }
        public string Status { get; set; }
        public System.DateTime DataOrcamento { get; set; }
        public string ProblemaIdentificado { get; set; }
        public Nullable<System.DateTime> DataInicialPrevista { get; set; }
        public Nullable<System.DateTime> DataInicial { get; set; }
        public Nullable<System.DateTime> DataFinal { get; set; }
        public Nullable<float> SubTotalServicos { get; set; }
        public Nullable<float> SubTotalMateriais { get; set; }
        public Nullable<float> ValorTotal { get; set; }
        public Nullable<float> ValorAPagar { get; set; }
        public string FormaPagamento { get; set; }
        public string InformacoesAdicionais { get; set; }
        public string AprovacaoCliente { get; set; }
        public Nullable<float> ValorDinheiro { get; set; }
        public Nullable<float> ValorCartao { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Veiculos Veiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosMateriais> OrdensServicosMateriais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdensServicosServicos> OrdensServicosServicos { get; set; }
    }
}
