//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculos
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> MarcaVeiculoId { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Placa { get; set; }
        public string TipoCompustivel { get; set; }
        public string Observacoes { get; set; }
        public string CategoriaCarro { get; set; }
        public string TipoMotor { get; set; }
    
        public virtual MarcasCarros MarcasCarros { get; set; }
        public virtual Clientes Clientes { get; set; }
    }
}
