//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Veiculos
    {
        public int Id { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public int MarcaVeiculoId { get; set; }
        public string Modelo { get; set; }
        public int Ano { get; set; }
        public string Placa { get; set; }
        [Display(Name = "Categoria do carro")]
        public string CategoriaCarro { get; set; }
        [Display(Name = "Tipo de combustível")]
        public string TipoCompustivel { get; set; }
        [Display(Name = "Tipo do motor")]
        public string TipoMotor { get; set; }
        [Display(Name = "Observações")]
        public string Observacoes { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual MarcasCarros MarcasCarros { get; set; }
    }
}
